version: '3.8'

services:
  httpd:
    image: httpd:2.4
    restart: always
    container_name: httpd
    depends_on:
      - traccar
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Europe/Berlin
    security_opt:
     - label=disable
    volumes:
    - type: bind
      source: ./compose/local/httpd/usr/local/apache2/conf/httpd.conf
      target: /usr/local/apache2/conf/httpd.conf
      read_only: true
    - type: bind
      source: ./compose/local/httpd/etc/apache2/sites-available/traccar.conf
      target: /etc/apache2/sites-available/traccar.conf
      read_only: true
    
  traccar:
    image: traccar/traccar:4.10-debian
    restart: always
    container_name: traccar
    depends_on:
      - mysql
    ports:
    #  - "80:8082"
      - "5000-5150:5000-5150"
      - "5000-5150:5000-5150/udp"
    environment:
      TZ: Europe/Berlin
    security_opt:
     - label=disable
    volumes:
    - type: bind
      source: /var/log/container/traccar
      target: /opt/traccar/logs
    - type: bind
      source: ./compose/local/traccar/traccar.xml
      target: /opt/traccar/conf/traccar.xml
      read_only: true

  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    container_name: mysql
    environment:
       TZ: Europe/Berlin
    security_opt:
     - label=disable
    volumes:
     - type: bind
       source: /mnt/dat/db/mysql
       target: /var/lib/mysql
     - type: bind
       source: ./compose/local/mysql/my.cnf
       target: /etc/my.cnf
       read_only: true
